app/modules/boxgallery/controllers/AController.php
<?php
namespace app\modules\boxgallery\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\easyii\behaviors\SortableDateController;
use yii\widgets\ActiveForm;
use yii\web\UploadedFile;

use yii\easyii\components\Controller;
use app\modules\boxgallery\models\BoxGallery;
use yii\easyii\helpers\Image;
use yii\easyii\behaviors\StatusController;

class AController extends Controller
{
    public function behaviors()
    {
        return [
            
            [
                'class' => StatusController::className(),
                'model' => BoxGallery::className()
            ]
        ];
    }

    public function actionIndex()
    {
        $data = new ActiveDataProvider([
            'query' => BoxGallery::find(),
        ]);

        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionCreate()
    {
        $model = new BoxGallery;
		$model->date_created = date('Y-m-d h:i:s');

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
             else{
                if(isset($_FILES) && $this->module->settings['enableThumb']){
                    $model->image = UploadedFile::getInstance($model, 'image');
					$model->thumb_image = UploadedFile::getInstance($model, 'thumb_image');
                    if($model->image && $model->validate(['image'])){
                        $model->image = Image::upload($model->image, 'boxgallery');
                    }
                    else{
                        $model->image = '';
                    }
					if($model->thumb_image && $model->validate(['thumb_image'])){
                        $model->thumb_image = Image::upload($model->thumb_image, 'boxgallery');
                    }
                    else{
                        $model->thumb_image = '';
                    }
                }
                
                $model->tag_id = $_POST['BoxGallery']['tag_id'] ? implode(",",$_POST['BoxGallery']['tag_id']):'';
                $boxname_exist= BoxGallery::Checkboxname($model->boxname);
                if($boxname_exist!=1)
                {
					if($model->save()){
						$update = BoxGallery::Updateboxtag($model->id,$model->tag_id);
					   
						$this->flash('success', Yii::t('easyii/boxgallery', 'BoxGallery created'));
						return $this->redirect(['/admin/'.$this->module->id]);
					}
					else{
						$this->flash('error', Yii::t('easyii', 'Create error. {0}', $model->formatErrors()));
						return $this->refresh();
					}
				}else{
					$this->flash('error', Yii::t('easyii', 'Box name already exist'));
					return $this->refresh();
				}
            }
        }
        else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    public function actionEdit($id)
    {
        $model = BoxGallery::findOne($id);
		$model->date_updated = date('Y-m-d h:i:s');

        if($model === null){
            $this->flash('error', Yii::t('easyii', 'Not found'));
            return $this->redirect(['/admin/'.$this->module->id]);
        }

        if ($model->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            else{
                if(isset($_FILES) && $this->module->settings['enableThumb']){
                    $model->image = UploadedFile::getInstance($model, 'image');
					$model->thumb_image = UploadedFile::getInstance($model, 'thumb_image');
                    if($model->image && $model->validate(['image'])){
                        $model->image = Image::upload($model->image, 'boxgallery');
                    }
                    else{
                        $model->image = $model->oldAttributes['image'];
                    }
					
					if($model->thumb_image && $model->validate(['thumb_image'])){
                        $model->thumb_image = Image::upload($model->thumb_image, 'boxgallery');
                    }
                    else{
                        $model->thumb_image = $model->oldAttributes['thumb_image'];
                    }
                }
               $model->tag_id = $_POST['BoxGallery']['tag_id'] ? implode(",",$_POST['BoxGallery']['tag_id']):'';
               
                if($model->save()){
					$update = BoxGallery::Updateboxtag($model->id,$model->tag_id);
					   
                    $this->flash('success', Yii::t('easyii/boxgallery', 'BoxGallery updated'));
                }
                else{
                    $this->flash('error', Yii::t('easyii', 'Update error. {0}', $model->formatErrors()));
                }
                return $this->refresh();
            }
        }
        else {
            return $this->render('edit', [
                'model' => $model
            ]);
        }
    }

    public function actionPhotos($id)
    {
        if(!($model = BoxGallery::findOne($id))){
            return $this->redirect(['/admin/'.$this->module->id]);
        }

        return $this->render('photos', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        if(($model = BoxGallery::findOne($id))){
            $model->delete();
        } else {
            $this->error = Yii::t('easyii', 'Not found');
        }
        return $this->formatResponse(Yii::t('easyii/boxgallery', 'Box gallery deleted'));
    }

    public function actionClearImage($id,$key)
    {
        $model = BoxGallery::findOne($id);

        if($model === null){
            $this->flash('error', Yii::t('easyii', 'Not found'));
        }
        else{

		switch($key)
		{
			case 'image':
				$model->image = '';
				@unlink(Yii::getAlias('@webroot').$model->image);
			break;
			
			case 'thumb_image':
				$model->thumb_image = '';
				@unlink(Yii::getAlias('@webroot').$model->thumb_image);
			break;
		}
            if($model->update()){
                @unlink(Yii::getAlias('@webroot').$model->image);
                $this->flash('success', Yii::t('easyii', 'Image cleared'));
            } else {
                $this->flash('error', Yii::t('easyii', 'Update error. {0}', $model->formatErrors()));
            }
        }
        return $this->back();
    }

    public function actionUp($id)
    {
        return $this->move($id, 'up');
    }

    public function actionDown($id)
    {
        return $this->move($id, 'down');
    }

    public function actionOn($id)
    {
        return $this->changeStatus($id, BoxGallery::STATUS_ON);
    }

    public function actionOff($id)
    {
        return $this->changeStatus($id, BoxGallery::STATUS_OFF);
    }
}

app/modules/boxgallery/views/a/_form.php
<?php
use yii\easyii\widgets\DateTimePicker;
use yii\easyii\helpers\Image;
use yii\easyii\widgets\TagsInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\easyii\widgets\Redactor;
use yii\easyii\widgets\SeoForm;

$module = $this->context->module->id;
if($model->tag_id){
	$model->tag_id = explode(",",$model->tag_id);
}
?>
<?php $form = ActiveForm::begin([
    'enableAjaxValidation' => true,
    'options' => ['enctype' => 'multipart/form-data', 'class' => 'model-form']
]); ?>
<?= $form->field($model, 'title') ?>

<?php if($this->context->module->settings['enableThumb']) : ?>
    <?php if($model->image) : ?>
    	<?php if(Yii::$app->homeUrl){?>
        <img src="<?= Yii::$app->homeUrl.Image::thumb($model->image, 240) ?>">
     <?php }else{ ?>
     	<img src="<?= Image::thumb($model->image, 240) ?>">
     <?php } ?>	
        <a href="<?= Url::to(['/admin/'.$module.'/a/clear-image', 'id' => $model->id]) ?>" class="text-danger confirm-delete" title="<?= Yii::t('easyii', 'Clear Image')?>"><?= Yii::t('easyii', 'Clear Image')?></a>
    <?php endif; ?>
    <?= $form->field($model, 'image')->fileInput() ?>
<?php endif; ?>

<?php if($this->context->module->settings['enableThumb']) : ?>
    <?php if($model->thumb_image) : ?>
		<?php if(Yii::$app->homeUrl){?>
        <img src="<?= Yii::$app->homeUrl.Image::thumb($model->thumb_image, 240) ?>">
     <?php }else{ ?>
     	<img src="<?= Image::thumb($model->thumb_image, 240) ?>">
     <?php } ?>
        <a href="<?= Url::to(['/admin/'.$module.'/a/clear-image', 'id' => $model->id,'key' =>'thumb_image']) ?>" class="text-danger confirm-delete" title="<?= Yii::t('easyii', 'Clear Thumb Image')?>"><?= Yii::t('easyii', 'Clear Thumb Image')?></a>
    <?php endif; ?>
    <?= $form->field($model, 'thumb_image')->fileInput() ?>
<?php endif; ?>

<?php echo $form->field($model, 'boxname')->dropDownList(['box1' => 'Box 1', 'box2' => 'Box  2', 'box3' => 'Box 3','box4' => 'Box 4','box5' => 'Box 5'
,'box6' => 'Box 6', 'box7' => 'Box  7', 'box8' => 'Box 8']); ?>
<?= $form->field($model, 'tag_id')            
         ->dropDownList($model->CategoryDropdown,
         [
          'multiple'=>'multiple',
          'class'=>'chosen-select input-md required', 
          'size'=>'4',             
         ]             
        )->label("Add Tag"); ?>

<?= $form->field($model, 'activate_url')->checkbox() ?>

<?= $form->field($model, 'url') ?>

<?php if(IS_ROOT) : ?>
    <?= $form->field($model, 'slug') ?>
    <?= SeoForm::widget(['model' => $model]) ?>
<?php endif; ?>

<?= Html::submitButton(Yii::t('easyii', 'Save'), ['class' => 'btn btn-primary']) ?>
<?php ActiveForm::end(); ?>

app/modules/boxgallery/views/a/_menu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>
<ul class="nav nav-pills">
    <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
        <a href="<?= $this->context->getReturnUrl(['/admin/'.$module]) ?>">
            <?php if($action == 'edit' || $action == 'photos') : ?>
                <i class="glyphicon glyphicon-chevron-left font-12"></i>
            <?php endif; ?>
            <?= Yii::t('easyii', 'List') ?>
        </a>
    </li>
    <li <?= ($action === 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/create']) ?>"><?= Yii::t('easyii', 'Create') ?></a></li>
</ul>
<br/>

app/modules/boxgallery/views/a/_submenu.php
<?php
use yii\helpers\Url;

$action = $this->context->action->id;
$module = $this->context->module->id;
?>

<ul class="nav nav-tabs">
    <li <?= ($action === 'edit') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/edit', 'id' => $model->primaryKey]) ?>"><?= Yii::t('easyii/boxgallery', 'Edit Boxgallery Category') ?></a></li>
    </ul>
<br>

app/modules/boxgallery/views/a/create.php
<?php
$this->title = Yii::t('easyii/boxgallery', 'Create Box Gallery');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

app/modules/boxgallery/views/a/edit.php
<?php
$this->title = $model->title;
?>
<?= $this->render('_menu') ?>

<?php if($this->context->module->settings['enablePhotos']) echo $this->render('_submenu', ['model' => $model]) ?>

<?= $this->render('_form', ['model' => $model]) ?>

app/modules/boxgallery/views/a/index.php
<?php
use app\modules\boxgallery\models\BrandCategories;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = Yii::t('easyii/boxgallery', 'Box Gallery');

$module = $this->context->module->id;
?>

<?= $this->render('_menu') ?>

<?php if($data->count > 0) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <?php if(IS_ROOT) : ?>
                    <th width="50">#</th>
                <?php endif; ?>
                <th><?= Yii::t('easyii', 'Box') ?></th>
                <th><?= Yii::t('easyii', 'Title') ?></th>
                <th><?= Yii::t('easyii', 'Date Created') ?></th>
                <th><?= Yii::t('easyii', 'Date Updated') ?></th>
                <th width="100"><?= Yii::t('easyii', 'Status') ?></th>
                <th width="120"></th>
            </tr>
        </thead>
        <tbody>
    <?php foreach($data->models as $item) : ?>
            <tr data-id="<?= $item->primaryKey ?>">
                <?php if(IS_ROOT) : ?>
                    <td><?= $item->primaryKey ?></td>
                <?php endif; ?>
                 <td><?=ucwords( $item->boxname) ?></td>
                <td><a href="<?= Url::to(['/admin/'.$module.'/a/edit/', 'id' => $item->primaryKey]) ?>"><?= $item->title ?></a></td>
                <td><?= $item->date_created ?></td>
                <td><?= $item->date_updated ?></td>
                <td class="status">
                    <?= Html::checkbox('', $item->status == BrandCategories::STATUS_ON, [
                        'class' => 'switch',
                        'data-id' => $item->primaryKey,
                        'data-link' => Url::to(['/admin/'.$module.'/a']),
                    ]) ?>
                </td>
                <td>
                    <div class="btn-group btn-group-sm" role="group">
                        <a href="<?= Url::to(['/admin/'.$module.'/a/up', 'id' => $item->primaryKey]) ?>" class="btn btn-default move-up" title="<?= Yii::t('easyii', 'Move up') ?>"><span class="glyphicon glyphicon-arrow-up"></span></a>
                        <a href="<?= Url::to(['/admin/'.$module.'/a/down', 'id' => $item->primaryKey]) ?>" class="btn btn-default move-down" title="<?= Yii::t('easyii', 'Move down') ?>"><span class="glyphicon glyphicon-arrow-down"></span></a>
                        <a href="<?= Url::to(['/admin/'.$module.'/a/delete', 'id' => $item->primaryKey]) ?>" class="btn btn-default confirm-delete" title="<?= Yii::t('easyii', 'Delete item') ?>"><span class="glyphicon glyphicon-remove"></span></a>
                    </div>
                </td>
            </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
    <?= yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ]) ?>
<?php else : ?>
    <p><?= Yii::t('easyii', 'No records found') ?></p>
<?php endif; ?>

app/modules/boxgallery/views/a/photos.php
<?php
use yii\easyii\widgets\Photos;

$this->title = $model->title;
?>

<?= $this->render('_menu') ?>
<?= $this->render('_submenu', ['model' => $model]) ?>

<?= Photos::widget(['model' => $model])?>